apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus   
    prometheus: prometheus
  name: prometheus-service
spec:
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus
    prometheus: prometheus