---
apiVersion: v1
kind: Service
metadata:
  name: my-app-myapp
  labels:
    helm.sh/chart: myapp-0.2.0
    app.kubernetes.io/name: myapp
    app.kubernetes.io/version: "1.16.0"
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: my-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-myapp
  labels:
    helm.sh/chart: myapp-0.2.0
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: my-app
    app.kubernetes.io/version: "1.16.0"
spec:
  replicas: 2
  selector:
    matchlabels:
      app.kubernetes.io/name: myapp
      app.kubernetes.io/instance: my-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
        app.kubernetes.io/instance: my-app
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
      - name: myapp
          image: tomcat:latest
          command: ["/bin/sh"]
          args: ["-c","sh /usr/local/tomcat/bin/startup.sh;while true; do echo hello; sleep 10;done"]
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 60
          #   periodSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          #   timeoutSeconds: 10
          resources:
            requests:
              memory: 0.25Gi
              cpu: 0.5
            limits:
              memory: 0.25Gi 
              cpu: 0.5
