apiVersion: v1
kind: ConfigMap
metadata:
  name: conversion-script
data:
  conversion.sh: |
    curl -s https://deekshithsn.free.beeceptor.com/appstatus > /usr/share/prom/file
    # coverting it to time series from json which is key value 
    jq -r 'keys_unsorted[] as $k | "\($k) \(.[$k])"' /usr/share/prom/file > /usr/share/prom/metrics.txt
    # prometheus only accepts 4 types of data which are Counter, Gauge, Histogram and Summary so converting true and false to 0' and 1's respectively    
    sed -i 's/true/1/g' /usr/share/prom/metrics.txt
    sed -i 's/false/0/g' /usr/share/prom/metrics.txt
    # converting metrics which will understood by prometheus
    sed -i 'h;:a;s/\n/&/1;t;G;ba' /usr/share/prom/metrics.txt
    sed -i 's/.*/#&/;n' /usr/share/prom/metrics.txt
    awk -F '1' '{for (i=1; i<NF; i++) {OFS=c%2?FS:"gauge"; printf "%s%s", $i, OFS; c++} print $NF}' /usr/share/prom/metrics.txt > /usr/share/prom/final_tem.txt
    awk -F '0' '{for (i=1; i<NF; i++) {OFS=c%2?FS:"gauge"; printf "%s%s", $i, OFS; c++} print $NF}' /usr/share/prom/final_tem.txt >  /usr/share/prom/final.txt
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pythonprom
data:
  index.py: |
    from flask import Flask

    app = Flask(__name__)
    @app.route("/metrics", methods=['GET'])
    def getfile():
        with open("/usr/share/prom/final.txt", "r+") as f:
            data = f.read()
        return data

    if __name__ == '__main__':
        app.run(host='0.0.0.0')

---

apiVersion: v1
kind: Service
metadata:
  name: metrics-endpoint
  labels:
    app: metrics-app
spec:
  type: NodePort
  ports:
    - name: "http"
      targetPort: 5000
      port: 5000
  selector:
    app: metrics-app

---

apiVersion: v1
kind: Pod
metadata:
  name: metrics-pod
  labels:
    app: metrics-app
spec:
  volumes:
  - name: shared
    emptyDir: {}
  - name: conscript 
    configMap:
      name: "conversion-script"
  - name: python-volume
    configMap:
      name: "pythonprom"
  containers:
  - name: jsontotimeseriesconversion
    image: dwdraju/alpine-curl-jq
    command: ["/bin/sh"]
    args: ["-c",  "cp /usr/share/scripts/conversion.sh /usr/share/conversion.sh;while true; do  chmod 777 /usr/share/conversion.sh; /usr/share/conversion.sh ; sleep 10; done"]
    volumeMounts:
    - name: shared
      mountPath: /usr/share/prom
    - name: conscript
      mountPath: /usr/share/scripts/conversion.sh
      subPath: conversion.sh

  - name: exposemetrics
    image: python:3
    command: ["/bin/sh"]
    args: ["-c", "pip install flask flask_cors;while true; do python /usr/share/python/index.py ; sleep 10; done"]
    ports:
      - containerPort: 5000
    volumeMounts:
    - name: shared
      mountPath: /usr/share/prom
    - name: python-volume
      mountPath: /usr/share/python/index.py
      subPath: index.py
